import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Link from "next/link";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} antialiased max-w-230 mx-auto min-h-screen font-sans px-4`}
      >
        <ThemeProvider>
          {children}
          <footer className="border-t mt-18 flex items-center justify-center pt-8 pb-4">
            <p className="text-sm font-medium flex flex-col items-center gap-2">
              © 2026 Jelmar Rapis. All rights reserved.
              <span className="font-normal">
                This portfolio website is inspired by{" "}
                <Link href="https://bryllim.com/" className="underline">
                  Bryl Lim.
                </Link>
              </span>
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
